FROM node:lts-alpine3.22 AS build_js

WORKDIR /usr/local/build

COPY . .

RUN npm install

RUN npm run build

FROM node:lts-alpine3.22 AS build_depedency

WORKDIR /usr/local/build

COPY . .

RUN npm install --production

FROM node:lts-alpine3.22 AS prod

WORKDIR /usr/local

COPY --from=build_js /usr/local/build/build ./build
COPY --from=build_depedency /usr/local/build/node_modules ./node_modules

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]

CMD [ "/usr/local/build/main.js" ]