FROM node:latest AS build

WORKDIR /app

COPY . .

RUN npm i

RUN npm run build

FROM node:alpine3.21

WORKDIR /app

COPY --from=build /app/build .
COPY --from=build /app/node_modules /app/node_modules

CMD ["node", "app.js"]